version: '3'
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      REDIS_HOST: db
      REDIS_PASS: password
      REDIS_PORT: 6379
  db:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass password
